version: '3.8'

services:
  mysql-shard1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shard1
    ports:
      - "3307:3306"
    volumes:
      - shard1_data:/var/lib/mysql

  mysql-shard2:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shard2
    ports:
      - "3308:3306"
    volumes:
      - shard2_data:/var/lib/mysql

volumes:
  shard1_data:
  shard2_data:


